version: 0.2

env:
  variables:
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 017789174567.dkr.ecr.us-east-1.amazonaws.com/spring-demo-aws

  build:
    commands:
      - docker build -t springboot-app .
      - docker tag springboot-app:latest 017789174567.dkr.ecr.us-east-1.amazonaws.com/spring-demo-aws:latest

  post_build:
    commands:
      - docker push 017789174567.dkr.ecr.us-east-1.amazonaws.com/spring-demo-aws:latest
      - printf '[{"name":"springboot-container","imageUri":"%s"}]' 017789174567.dkr.ecr.us-east-1.amazonaws.com/spring-demo-aws:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
